<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RazerMixerBridge-1fa087d3-9486-44ea-872b-710591e45e5e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="8.0.1" />
    <PackageReference Include="Tomlyn" Version="2.4.0" />
  </ItemGroup>
</Project>
